language: csharp
solution: SSQLib.sln
env:
 global:
  - EnableNuGetPackageRestore=true
install:
 - nuget install xunit.runners -Version 1.9.2 -OutputDirectory packages
script:
 - xbuild /p:Configuration=Release SSQLib.sln
 - mono ./packages/xunit.runners.1.9.2/tools/xunit.console.clr4.exe Artifacts/bin/Test.SSQLib/Test.SSQLib.dll
