language: csharp
solution: SSQLib.sln
env:
 global:
  - EnableNuGetPackageRestore=true
install:
 - nuget install xunit.runner.console -Version 2.0.0 -OutputDirectory packages
script:
 - xbuild /p:Configuration=Release SSQLib.sln
 - cd Artifacts/bin/Test.SSQLib/
 - mono ../../../packages/xunit.runner.console.2.0.0/tools/xunit.console.exe Test.SSQLib.dll
