language: csharp
solution: SSQLib.sln
install:
- nuget restore SSQLib.sln
- nuget install xunit.runners -Version 2.0.0 -OutputDirectory testrunner
script:
 - xbuild /p:Configuration=Release SSQLib.sln
 - mono testrunner/xunit.runner.console.2.0.0/tools/xunit.console.exe Artifacts/bin/Test.SSQLib/Test.SSQLib.dll
